entrecalle/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.defaults import *
from django.contrib.auth import views as auth_views
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

# importamos settings
from entrecalle import settings

handler404 = "entrecalle_app.views.handler404"
handler500 = "entrecalle_app.views.handler500"

 
urlpatterns = patterns('',
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    url(r'^admin/', include(admin.site.urls)),
    #aqui comienzan las urls de entrecalle
    url(r'', include('multiuploader.urls')),
    url(r'^$', 'entrecalle_app.views.index', name='index'),

    
    url(r'^register/$', 'entrecalle_app.views.register', name='register'),
    url(r'^login/$', 'entrecalle_app.views.login', name='login'),
    url(r'^logout/$', 'entrecalle_app.views.logout', name='logout'),
    url(r'^user/$', 'entrecalle_app.views.infoUser', name='infoUser'),
    url(r'^user/info$', 'entrecalle_app.views.infoUser_ajax', name='infoUser_ajax'),





    url(r'^terminos/$', 'entrecalle_app.views.terminos', name='Terminos'),
    url(r'^privacidad/$', 'entrecalle_app.views.privacidad', name='Privacidad'),
    url(r'^password/$', 'entrecalle_app.views.passord_reset', name='Reset'),



    
    
    url(r'^building/add/$', 'entrecalle_app.building.build_add', name='build_add'),
    url(r'^building/view/(\d+)/$', 'entrecalle_app.building.build_view', name='build_view'),
    url(r'^building/photo/add/(\d+)/$', 'entrecalle_app.building.building_photo_render', name='building_photo_render'),
    url(r'^building/photo/add/ajax$', 'entrecalle_app.building.building_photo_ajax', name='building_photo_ajax'),
    url(r'^building/json/$', 'entrecalle_app.services.building_json', name='build_json'),
    url(r'^building/add/cronica/$', 'entrecalle_app.building.Agregar_Cronica', name='Agregar_Cronica'),
    

    # Reseteo de password
    #url(r'^passreset/$',auth_views.password_reset,{'template_name': 'forgot_password.html'},name='forgot_password1',),
    url(r'^forgot_password/$',auth_views.password_reset,name='forgot_password1'),
    url(r'^forgot_password/done/$',auth_views.password_reset_done,name='forgot_password2'),
    url(r'^forgot_password/confirm/(?P<uidb36>[-\w]+)/(?P<token>[-\w]+)/$',auth_views.password_reset_confirm,name='forgot_password3'),
    url(r'^forgot_password/complete/$',auth_views.password_reset_complete,name='forgot_password4'),
    
    #url(r'^style/add/$', 'entrecalle_app.views.style_add', name='style_add'),
    
)

entrecalle_app/models.py
from django.db import models
from datetime import date
from django.contrib.auth.models import User
import cloudinary
from cloudinary.models import *

# Create your models here.

class Intere(models.Model):

    interes = models.CharField(max_length=200)

    def __unicode__(self):
        return self.interes
    
class Informacion_personale(models.Model):
    
    user = models.OneToOneField(User)
    pais = models.CharField(max_length = 30,null=True,blank=True)
    sexo = models.CharField(max_length=1, choices=(('H', 'Hombre'), ('M', 'Mujer')))
    areas_interes = models.ManyToManyField(Intere,null=True,blank=True)
    permisos = models.IntegerField(default = 4)
    ranknig = models.BigIntegerField(default = 0)
    foto_perfil = CloudinaryField('foto_url',null=True,blank=True)
    noticias = models.BooleanField(default=True)
    N_Comentarios = models.BigIntegerField(default = 0)
    N_Fotografias = models.BigIntegerField(default = 0)
    N_Resenas = models.BigIntegerField(default = 0)
    N_Biografias = models.BigIntegerField(default = 0)
    
    
class Categoria(models.Model):
    
    categoria_id = models.AutoField(primary_key=True)
    categoria_tipo = models.CharField(max_length=50)
    imagen = CloudinaryField('imagen')
    
    def __unicode__(self):
        return self.categoria_tipo
    
class Edificio(models.Model):
    
    edificio_id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=200)
    categoria = models.ForeignKey(Categoria,null=True,blank=True,default=1)
    descripcion = models.TextField(null=True,blank=True)
    direccion = models.CharField(max_length = 300,null=True,blank=True)
    foto_url = CloudinaryField('foto_url')
    longitud = models.CharField(max_length=30,null=True,blank=True)
    latitud = models.CharField(max_length=30,null=True,blank=True)

    def __unicode__(self):
        return self.nombre
    
class Imagene(models.Model):
    
    imagen_id = models.AutoField(primary_key=True)
    url = CloudinaryField('foto_url')
    edificio = models.ForeignKey(Edificio)
    tipo = models.CharField(max_length=2,default=0)
    usuario = models.CharField(max_length=15)

class Cronica(models.Model):

    edificio = models.ForeignKey(Edificio)
    cronica = models.CharField(max_length=121)
    usuario = models.CharField(max_length=50)
    fecha = models.CharField(max_length=11)

templates/Edificio/add_photo.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>
      <title></title>
      {% load multiuploader %}
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
      <link rel="stylesheet" type="text/css" href="{{MEDIA_URL}}/css/agrega.css" />
      <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js"></script>
      <script src="http://cdn.jquerytools.org/1.2.7/full/jquery.tools.min.js"></script>
      <script type="text/javascript">
            $(document).ready(function(){
            $("#id").val("{{edificio_id}}");
            });
      </script>
</head>
<body>
      <div id="main">
          <div class="wrapper_big">
              <div class="contentab">

                  <h2><strong>{{nombre}}</strong></h2>
                  <br />
                  <div id="pics">
                        <!--
                        <div class="content_pic">
                              <div class="photo_"><img src="{{MEDIA_URL}}/images/dummys/140x140.png"/></div>
                              <div class="creditos">
                                    <span>Créditos de la imagen</span>
                                    <span><input name="" type="radio" value="propia" /><label>Propia</label></span>
                              </div>
                              <div class="tipo_imagen">
                                    <span>Tipo de imágen</span>
                                    <span><input name="" type="radio" value="propia" /><label>Actual</label></span>
                                    <span><input name="" type="radio" value="propia" /><label>Antigua</label></span>
                                    <span><input name="" type="radio" value="propia" /><label>Sketchbook</label></span>
                              </div>
                        </div>
                        -->

                        {% multiupform %}

                  </div>
                  <!--content--> 
            </div>
            <!--wrapper_big--> 
      </div>
      <!--main-->

</body>
</html>

templates/Edificio/build_view.html
{% extends "Includes/header.html" %}

{% block body %}
<div id="fb-root"></div>
<script type="text/javascript">    

function remplazos(){
  var contenedor = document.getElementById("contenedor");
  var Cronica_Nueva = document.getElementById("LaCronica").value;

  var Caja = document.getElementById("LaCronica");

  var cronica = document.createElement("div");
  cronica.setAttribute("class","cronica");

  var f_cronica = document.createElement("div");
  f_cronica.setAttribute("class","f_cronica");

  var ima = document.createElement("img");
  ima.setAttribute("src","{{Informacion.foto}}");
  ima.setAttribute("width","100");
  ima.setAttribute("height","100");

  var txt_c = document.createElement("div");
  txt_c.setAttribute("class","txt_c");

  var cronica_txt = document.createElement("div");
  cronica_txt.setAttribute("class","cronica_txt")
  cronica_txt.appendChild(document.createTextNode(Caja.value));

  document.getElementById("LaCronica").value = "";

  f_cronica.appendChild(ima);
  txt_c.appendChild(cronica_txt);
  
  cronica.appendChild(f_cronica);
  cronica.appendChild(txt_c);
  contenedor.appendChild(cronica);
  //contenedor.appendChild(txt_c);
}
$(document).ready(function() {
  $('#single').toggleButton({'selectionMode':'single'});
  $('#normal').toggleButton();
  $('#preselected').toggleButton();
  $('#imgholder').toggleButton({'buttonSelector':'.toggleBtn div'});
  $("#AgregarCronica").click(function(){
    $.get("/building/add/cronica/",{
      LaCronica:$('#LaCronica').val(),
      edifID:$('#Id_del_edificio').val(),
    },
    function(data) {
      $("#mensaje").text(data);
    }
    //algo();
    );
    remplazos();
      //window.location.reload();
      return false;
      //window.location.reload();
    });


});

</script>
<div id="sections">
  <section>
    <div id="middle_s">
      <div id="left">
        <div id="wrapper_left">
          <div id="blankWrapper">
            <div class="space"></div>
          </div>
          <!--end blank Wrapper--> 

        </div>
        <!--end Wrapper Left-->
        
        <div id="slider">
          <div class="types">{{ info_edificio.nombre}}</div>
          <div class="denuncia">
            <div class="bad">
              <div id="imgholder">
                <div class="toggleBtn">

                  <!--
                  <div id="buttonImg"></div>
                  <span>Denuncia Olvidado </span>
                  <input type="checkbox" name="imgdemo" id="denuncia" value="3" />
                -->
              </div>
            </div>
          </div>
        </div>
        <div class="prettyContainer">
          <div class="image_carousel">
            <div id="foo2"> 
              <!--IMAGENES-->
              {% for imagen in info_edificio.imagenes %}
              <a rel="prettyPhoto[caroufredsel]" href="{{imagen}}"><img src="{{imagen}}" alt="{{info_edificio.nombre}}" width="125" height="125" /> </a>
              {% endfor %} 
            </div>
            <div class="clearfix"></div>
            <a class="prev" id="foo1_prev" href="#"><span>prev</span></a> <a class="next" id="foo1_next" href="#"><span>next</span></a> </div>
          </div>
        </div>
        <div class="clear"></div>
        <div id="mapa_edificio">
          <div class="types">Reseña</div>
            <!--
            <div class="edit_this">
              <div class="edit_button">Editar</div>
            </div>
          -->
          <div id="reseña_edificio">
            <div class="reseña_txt">
              <h2>Descripcion</h2>
              <div class="antecedentes">{{info_edificio.descripcion}}</div>
            </div>
          </div>
          <div class="mapa" id="mapa" style="height: 500px; width: 600px;"> <img src="{{MEDIA_URL}}/images/dummys/mapa600x500.png" width="600" height="500"/> </div>

          <div id="bio_autor">
            <div class="types">Datos lugar</div>
              <!--
              <div class="edit_this">
                <div class="edit_button">Editar</div>
              </div>
            -->
            <div id="info_edificio">
                <!--<div class="campo_vista">
                  <label>Autor</label>
                  <div class="input_txt">{{info_edificio.autor}}</div>
                </div>-->
                
                <div class="campo_vista">
                  <label>Ubicación</label>
                  <div class="input_txt">{{info_edificio.direccion}}</div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!--end left-->


      <!--end right--> 
    </div>
    <!--end middle--> 
  </section>
  <section id="foot">
    <div class="types">Participa y comparte algo que sepas de éste lugar.</div>
    <div id="cronicas">
      <div id="contenedor">
        {% for C,foto in Cronicas reversed%}
        <div class="cronica">
          <div class="f_cronica">
            {% if foto %}
            <img src="{{foto}}" width="100" height="100"/>
            {% else %}
            <img src="{{MEDIA_URL}}/images/dummys/dummy_user_m.png" width="100" height="100"/>
            {% endif %}
          </div>
          <div class="txt_c">
            <div class="cronica_txt">
              {{C.cronica}}
            </div>
            <div>
                        </div>
            <!--<div ID = "TESTING">
              {{info_edificio.test}}
            </div>-->
            <div>
              {{C.fecha}}
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
      {% if Informacion.menu %}
      <div class="cronica">
        <input type="hidden" id="Id_del_edificio" value="{{info_edificio.edificio_id}}">
        <div class="f_cronica">
                    {% if Informacion.foto %}
<img src="{{Informacion.foto}}" alt="profilepic" width="100" height="100"/>
                    {% else %}
                    <img src="{{MEDIA_URL}}/images/dummys/dummy_user_m.png" alt="profilepic" width="100" height="100"/>
                    {% endif %}
        </div>
        <div class="txt_c">
          <textarea name="" cols="" rows="4" id="LaCronica" maxlength="200"></textarea>
          <div id="c1"></div>
          <script type="text/javascript">
                                $('#LaCronica').keyup(function () {
                                    var left = 200 - $(this).val().length;
                                    if (left < 0) {
                                        left = 0;
                                    }
                                    $('#c1').text('Caracteres restantes: ' + left);
                                });
                
                                </script>
          <div class="addcomment" id="AgregarCronica">Publicar</div>
        </div>
      </div>
      {% endif %}
      
    </div>
  </section>
  <!--end foot--> 

</div>
<!--end wrapper-->
{% endblock %}

templates/Edificio/building_add.html
{% load cloudinary %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
    <head>
        <title></title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
		
        <!-- CSS -->
        <link rel="stylesheet" type="text/css" href="{{MEDIA_URL}}css/agrega.css" />
        <link rel="stylesheet" href="{{MEDIA_URL}}css/bootstrap.css" />

        <!-- JS -->
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
        <script src="http://cdn.jquerytools.org/1.2.7/full/jquery.tools.min.js"></script>
        <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places"></script>
        <script type="text/javascript" src="{{MEDIA_URL}}js/mapa.js" ></script>

    </head>
    <body onload="initialize()">
    <div id="main">
		<div class="wrapper_sbig">
        
		<div class="content"><br />
        <h1>Divulga un edificio, construcción o lugar que nadie ha compartido.</h1>
        <hr />
        <h2>Antes de empezar, recuerda verificar en el mapa de<span> Entrecalle</span> que no esté ya localizado</h2>
          <!--<div class="encabezado"></div>-->
				<div id="form_wrapper" class="form_wrapper">
         		    <div id="dropper">
                    <div id="areas">
              
                    <a href="/"><img src="{{MEDIA_URL}}images/logotipo_grande.png" alt="" width="254" height="254" /></a>
                        {% if mensaje_m %}
                       <div class="alert alert-error">
                        {{mensaje_m}}
                        </div>
                    {% endif %}

                            </div>

                    
                    </div>
                {{msn}}
                    <form class="edificio" action="" enctype="multipart/form-data" method="POST" >
                       {% csrf_token %}
                    
				    <div class="campo">
						<label>Nombre:</label>
						{{form.nombre}}
                      </div>
                      <div class="campo">
						<label>Categoria:</label>
						{{form.categoria}}
                      </div>

                            <div class="campo">
                        <label>Dirección</label>
                          {{form.direccion}}
                      </div>
                            
                            <div class="campo">
                            <label>Descripcion</label>
                                {{form.descripcion}}
                            <div id="c1"></div>
                    		</div>

                            <div class="campo">
                            <label>Imagen</label>
                                {{form.foto_url}}
                            </div>
                            
                            <!--script caracteres-->
							<script type="text/javascript">
                                $('#id_descripcion').keyup(function () {
                                    var left = 200 - $(this).val().length;
                                    if (left < 0) {
                                        left = 0;
                                    }
                                    $('#c1').text('Caracteres restantes: ' + left);
                                });
								
                                </script>
                           
                        {{form.longitud}}
                        {{form.latitud}}
						<div class="bottom">
						  <input type="submit" value="Publicar" />
						</div>

					</form>
                    

				<div class="clear"></div>
                <div id="mapa2">
                    <p style="color:red;margin-bottom:0px;padding-bottom:0px;">Elige la posición dando clic en el mapa</p>
    			<div id="mapa">
    			mapa(650x150)
   				 </div>
   				 </div>
				</div>
		</div>
		</div>
		

	  </div>
    </body>
</html>